services:
  api:
    build:
      context: .
      dockerfile: StelexarasApp.API/Dockerfile
    restart: always
    networks:
      - app-network
    depends_on:
      - db
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_HTTP_PORTS: "8080"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=Stelexaras;User Id=sa;Password=lore3389!;TrustServerCertificate=True"
    ports:
      - "8080:8080"
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "lore3389!"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./StelexarasApp.Application/Dockerfile      
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
      ASPNETCORE_HTTP_PORTS: "80"
      ConnectionStrings__DefaultConnection: "Server=db,1433;Database=Stelexaras;User Id=sa;Password=lore3389!;TrustServerCertificate=True"
    ports:
      - "3000:80"
    restart: always
    networks:
      - app-network
    depends_on:
      - api
      
  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
  heimdall:    
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Berlin
    ports:
      - "8090:80"
      - "8443:443"
    networks:
      - app-network
    volumes:
      - ./heimdall/config:/config
networks:
  app-network:
    driver: bridge    
volumes:
  portainer_data:
    # heimdall_config:# comment it if you prefer a unnamed volume
  