services:
  api:
    build:
      context: .
      dockerfile: StelexarasApp.API/Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - app-network
    depends_on:
      - db
    environment:
      ASPNETCORE_URLS: http://+:8080
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      SA_PASSWORD: "SA_PASSWORD"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    networks:
      - app-network

  frontend:
    build:
      dockerfile: ./StelexarasApp.Web/Dockerfile
      context: .
    ports:
      - "3000:80"
    restart: always
    networks:
      - app-network
    depends_on:
      - api
      
  portainer:
    image: portainer/portainer-ce
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: always
networks:
  app-network:
    driver: bridge
volumes:
  portainer_data: