@StelexarasApp.Web_HostAddress = http://localhost:5030

# GET all ekpaideuomenoi
GET {{StelexarasApp.Web_HostAddress}}/ekpaideuomenoi/
Accept: application/json

###

# GET a specific ekpaideuomenos by ID
GET {{StelexarasApp.Web_HostAddress}}/ekpaideuomenoi/1
Accept: application/json

###
# POST a new ekpaideuomenos
POST {{StelexarasApp.Web_HostAddress}}/ekpaideuomenoi
Content-Type: application/json
Accept: application/json

{
  "name": "New Student",
  "age": 20
}

###
# PUT to update an existing ekpaideuomenos
PUT {{StelexarasApp.Web_HostAddress}}/ekpaideuomenoi/1
Content-Type: application/json
Accept: application/json

{
  "id": 1,
  "name": "Updated Student",
  "age": 21
}

###
# DELETE an ekpaideuomenos by ID
DELETE {{StelexarasApp.Web_HostAddress}}/ekpaideuomenoi/1
Accept: application/json

###