global using StelexarasApp.Library.Dtos.Domi;
global using StelexarasApp.Library.QueryParameters;
global using StelexarasApp.Library.Dtos.People.Staff;
global using StelexarasApp.Library.Models.Atoma.Staff;
global using StelexarasApp.API.Authorization;
global using StelexarasApp.Library.Models;
global using StelexarasApp.DataAccess.Helpers;
global using StelexarasApp.Library.Models.Logs;
global using StelexarasApp.Services.Interfaces.People.Staff;