name: .NET CI

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'

    - name: Restore workloads
      run: dotnet workload restore 
        
    - name: Install dependencies
      run: dotnet restore StelexarasApp.CI.slnf

    - name: Build
      run: dotnet build StelexarasApp.CI.slnf --configuration Release --no-restore

    - name: Run tests
      run: dotnet test StelexarasApp.CI.slnf --configuration Release --no-build --filter "FullyQualifiedName!~StelexarasApp.Tests.IntegrationTests"

    - name: Run integration tests      
      env:
        RUN_INTEGRATION_TESTS: 1
      if: env.RUN_INTEGRATION_TESTS == '1'  
      run: dotnet test StelexarasApp.CI.slnf --configuration Release --no-build --filter "FullyQualifiedName~StelexarasApp.Tests.IntegrationTests"